language: node_js
sudo: required
services:
  - docker
node_js:
  - "stable"
cache:
  directories:
    - node_modules
    - bower_components
before_script:
  - npm install -g npm
  - npm install -g gulp bower
  - bower install
script:
  - gulp
  - docker build -t michaelcoll/anim-enfance-front:latest .
  - if [[ ! -z "$TRAVIS_TAG" ]]; then docker tag michaelcoll/anim-enfance-front:latest michaelcoll/anim-enfance-front:$TRAVIS_TAG ; fi
after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push tutum.co/michaelcoll/anim-enfance-front
