language: node_js
sudo: required
services:
  - docker
node_js:
  - "stable"
before_script:
  - npm install -g gulp bower
  - npm install
  - bower install
script:
  - gulp
  - docker build -t michaelcoll/anim-enfance-front:latest .
