language: node_js
sudo: required
services:
  - docker
node_js:
  - "stable"
before_script:
  - npm install -g npm
  - npm install -g gulp bower
  - bower install
script:
  - gulp
  - docker build -t tutum.co/michaelcoll/anim-enfance-front:latest .
  - docker push tutum.co/michaelcoll/anim-enfance-front:latest
